"""service offered branch key 

Revision ID: 5168f987bfdc
Revises: 4860e7f180bb
Create Date: 2020-11-21 10:56:21.039224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5168f987bfdc'
down_revision = '4860e7f180bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_offered', sa.Column('branch_key', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'service_offered', 'branch', ['branch_key'], ['id'])
    op.drop_column('service_offered', 'branch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_offered', sa.Column('branch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service_offered', type_='foreignkey')
    op.drop_column('service_offered', 'branch_key')
    # ### end Alembic commands ###
