"""sync added 

Revision ID: b6374b96937e
Revises: 4e6477f3b639
Create Date: 2020-11-20 12:38:53.512251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6374b96937e'
down_revision = '4e6477f3b639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_status', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('booking', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('booking_times', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('image_company', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('mpesa', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('online_booking', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('payments', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('recovery', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('service', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('service_offered', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('teller_booking', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_synced', sa.Boolean(), nullable=True))
    op.add_column('video', sa.Column('is_synced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'is_synced')
    op.drop_column('user', 'is_synced')
    op.drop_column('teller_booking', 'is_synced')
    op.drop_column('service_offered', 'is_synced')
    op.drop_column('service', 'is_synced')
    op.drop_column('recovery', 'is_synced')
    op.drop_column('payments', 'is_synced')
    op.drop_column('online_booking', 'is_synced')
    op.drop_column('mpesa', 'is_synced')
    op.drop_column('image_company', 'is_synced')
    op.drop_column('booking_times', 'is_synced')
    op.drop_column('booking', 'is_synced')
    op.drop_column('account_status', 'is_synced')
    # ### end Alembic commands ###
