"""branch id 

Revision ID: ec7b888c14a7
Revises: 0eb260335f8a
Create Date: 2020-11-22 08:47:29.083671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec7b888c14a7'
down_revision = '0eb260335f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_offered', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'service_offered', ['name'])
    op.drop_constraint('service_offered_ibfk_1', 'service_offered', type_='foreignkey')
    op.create_foreign_key(None, 'service_offered', 'branch', ['branch_id'], ['id'])
    op.drop_column('service_offered', 'branch_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_offered', sa.Column('branch_key', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service_offered', type_='foreignkey')
    op.create_foreign_key('service_offered_ibfk_1', 'service_offered', 'branch', ['branch_key'], ['id'])
    op.drop_constraint(None, 'service_offered', type_='unique')
    op.drop_column('service_offered', 'branch_id')
    # ### end Alembic commands ###
